# Generated by Django 5.0.6 on 2024-07-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_remove_purchase_stripe_price_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=220, null=True, unique=True),
        ),
    ]
