# Generated by Django 5.0.6 on 2024-07-10 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
        ('shop', '0008_remove_product_price_remove_product_stripe_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='stripe_price',
        ),
        migrations.AddField(
            model_name='purchase',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.price'),
        ),
    ]
