# Generated by Django 5.0.6 on 2024-07-13 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator])),
                ('product', models.CharField(choices=[('P', 'PhotoGPStoMetaData')], default='P', max_length=20)),
                ('contact_permission', models.BooleanField(default=False, verbose_name='Contact me with development updates')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='last_name',
            field=models.CharField(default='filler_name', max_length=100),
            preserve_default=False,
        ),
    ]
