# Generated by Django 5.1.5 on 2025-05-10 13:45

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdistributable',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='productdistributable',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productdistributable',
            name='title',
            field=models.CharField(default='none', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productdistributable',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='protected/'), upload_to=''),
        ),
    ]
