# Generated by Django 5.1.5 on 2025-05-10 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_productdistributable_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mac_arm_file',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mac_x86_file',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pc_file',
        ),
    ]
