# Generated by Django 5.0.6 on 2024-07-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_discount_price_product_stripe_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stripe_price',
            field=models.IntegerField(blank=True, default=9900, null=True),
        ),
    ]
