# Generated by Django 5.0.6 on 2024-07-08 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_stripe_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
