# Generated by Django 5.0.6 on 2024-07-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_product_price_remove_product_stripe_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='stripe_price_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=220, null=True, unique=True),
        ),
    ]
