# Generated by Django 5.0.6 on 2024-08-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_price_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carousel_image1',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='carousel_image2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
