# Generated by Django 5.1.4 on 2025-01-07 15:41

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_carousel_image1_product_carousel_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='protected/'), upload_to=''),
        ),
    ]
