# Generated by Django 5.1.4 on 2025-01-09 16:20

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_product_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='file',
            new_name='mac_arm_file',
        ),
        migrations.AddField(
            model_name='product',
            name='mac_x86_file',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='protected/'), upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='pc_file',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='protected/'), upload_to=''),
        ),
    ]
