# Generated by Django 5.1.4 on 2025-01-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_rename_file_product_mac_arm_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinstance',
            name='mac_download_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
