# Generated by Django 5.1.4 on 2025-01-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_productinstance_mac_download_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lightbox_image1',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
