# Generated by Django 5.1.5 on 2025-04-11 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_price_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='created_at',
        ),
    ]
