# Generated by Django 5.1.5 on 2025-05-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_productdescription_productdistributable'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdistributable',
            name='type',
            field=models.CharField(choices=[('PC', 'PC executable'), ('MAC_ARM', 'Mac silicon executable'), ('MAC_INTEL', ' Mac Intel executable')], default='none', max_length=120),
            preserve_default=False,
        ),
    ]
