# Generated by Django 5.1.5 on 2025-05-08 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_productdistributable_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDescriptionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('video', models.URLField(blank=True)),
                ('section_type', models.CharField(choices=[('MAIN', 'Main product description'), ('SHORT', 'Short product description'), ('ACCORDION', 'Features accordion'), ('VIDEO', 'Demo video'), ('CAROUSEL-IMAGE', 'Carousel product image'), ('LIGHTBOX-IMAGE', 'Lightbox product image')], max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='ProductDescription',
        ),
    ]
